version: 1.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: TaPpMsCJOhM2UZHWnV9mrI5mgxq1Htu++flJCtLIzeXqaBga3IGpLaQUvc4wFT6t
before_build:
- nuget restore RsStationApi.sln
build:
  project: RsStationApi.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    iex .\update-nuspec-version.ps1

    nuget pack .\nuget\RsStationApi.nuspec
after_test:
- packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  RsStationApi.Client.Tests\bin\release\RsStationApi.Client.Tests.dll" -output:coverage.xml
- packages\coveralls.io.1.3.2\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
- path: '*.nupkg'
  name: Nuget Package
deploy:
- provider: NuGet
  api_key:
    secure: dePxaLgKHoDvRJ1Mz1W2ngqlbW8+/O8EUkcUuswBgBe+B+S2SLBTikjnpWb+K3Ox
  skip_symbols: true
  on:
    branch: master